# state.py

from pydantic import BaseModel, Field

# This is the central state object that flows through your entire system
# Every node (coach, evaluator, reporter) will read and update this

class SessionState(BaseModel):
    
    # Unique ID for each session (can be simple for now)
    session_id: str

    # Mode of operation (we start with "reading")
    # Later you can extend to "science" and "ethics"
    mode: str = "reading"

    # The current paragraph / input text
    paragraph: str

    # The question generated by the coach node
    question: str = ""

    # The user's answer (filled later via UI)
    answer: str = ""

    # Score given by evaluator (0–2)
    score: int = 0

    # Feedback from evaluator
    feedback: str = ""

    final_summary: str = ""

    # Stores full interaction history (optional for now)
    # Example: [{"question": "...", "answer": "..."}]
    history: list = Field(default_factory=list)