# state.py

from pydantic import BaseModel, Field

# This is the central state object that flows through your entire system.
# Every node (coach, evaluator, reporter) reads and updates this object.
# Keeping all state here makes the flow easy to trace and debug.

class SessionState(BaseModel):

    # Unique ID for each session (simple string for now)
    session_id: str

    # Mode of operation — start with "reading"
    # Future modes: "science", "ethics"
    mode: str = "reading"

    # The current chunk of story text shown to the user.
    # coach_node reads this to generate a question.
    paragraph: str = ""

    # The question generated by coach_node
    question: str = ""

    # The user's typed answer (filled by the UI before calling evaluator_node)
    answer: str = ""

    # Score assigned by evaluator_node (0 = wrong, 1 = partial, 2 = correct)
    score: int = 0

    # Short feedback text from evaluator_node
    feedback: str = ""

    # Optional end-of-session summary from reporter_node
    final_summary: str = ""

    # --- Story mode fields (added for story-mode branch) ---

    # All chunks for the currently loaded story.
    # Populated once when the user clicks "Start Story".
    # Each element is a string (2 paragraphs joined with \n\n).
    story_chunks: list = Field(default_factory=list)

    # Index of the chunk currently being shown (0-based).
    # Incremented after the user submits a correct/partial answer.
    current_index: int = 0

    # Full interaction history — one entry per chunk attempt.
    # Example: [{"question": "...", "answer": "...", "score": 2}]
    # Future LangSmith tracing point: each entry maps to one graph run.
    history: list = Field(default_factory=list)